feat(servers_config): enable configs by default
Don't require `enabled: true` - helps distributions without
separate available/enabled directories and prevents error:
"Rendering SLS 'production:nginx.servers' failed: Jinja variable 'list
object' has no attribute 'enabled'"

Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>